### ISSUE TITLE
This addon can not work

### ISSUE THREAD

**Issue by meteormatt** [jvillalobos/Add-to-Collection#1]
I can not see the favorite button even after install this addon.
Maybe because addons.mozilla.org site update again?
I see other people face this problem in AMO review.
https://addons.mozilla.org/zh-CN/firefox/addon/add-to-collection/reviews/

**Comment by jvillalobos** [comment]
The description on the listing page explains that the add-on is broken due to some security restrictions applied to WebExtensions on AMO. [This bug explains a little more](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082). Sorry, but I don't have plans to fix this issue. The workaround is to create a new add-on using legacy APIs.
